buzz_as_guesser_train: false
buzzer:
  config: mlp
  gpu: 0
  n_cores: 16
  n_guesses: 50
expo_questions: data/internal/expo/2016_hsnct.csv

guesser_char_skip: 25
buzzer_char_skip: 25
expo_char_skip: 10
n_guesses: 50

use_pretrained_embeddings: true
word_embeddings: data/external/deep/glove.6B.300d.txt
embedding_dimension: 300

guessers:
  qanta.guesser.dan.DanGuesser:
    - batch_size: 512
      enabled: false
      gradient_clip: 0.25
      lowercase: true
      luigi_dependency: qanta.pipeline.guesser.EmptyTask
      n_hidden_layers: 1
      n_hidden_units: 1000
      n_wiki_sentences: 5
      nn_dropout: 0.5
      use_wiki: false
      wiki_title_replace_token: ''
      combined_ngrams: true
      unigrams: true
      bigrams: false
      trigrams: false
      pooling: avg # [avg, max]
      combined_max_vocab_size: 300000
      unigram_max_vocab_size: null
      bigram_max_vocab_size: 50000
      trigram_max_vocab_size: 50000
      random_seed: null
  qanta.guesser.rnn.RnnGuesser:
    - batch_size: 128
      enabled: false
      gradient_clip: 0.25
      lowercase: true
      luigi_dependency: qanta.pipeline.guesser.EmptyTask
      n_hidden_layers: 1
      n_hidden_units: 1500
      n_wiki_sentences: 5
      dropout: 0.25
      use_wiki: false
      wiki_title_replace_token: ''
      random_seed: null
  qanta.guesser.elmo.ElmoGuesser:
    - enabled: false
      luigi_dependency: qanta.pipeline.guesser.EmptyTask
      random_seed: null
      dropout: .5
  qanta.guesser.elasticsearch.ElasticSearchGuesser:
    - enabled: false
      luigi_dependency: qanta.pipeline.guesser.EmptyTask
      many_docs: false
      n_cores: 15
      normalize_score_by_length: true
      qb_boost: 1
      use_all_wikipedia: false
      use_qb: true
      use_wiki: true
      wiki_boost: 1
      random_seed: null
      similarity:
        name: BM25 # [default, BM25]
        k1: 2.0
        b: 0.75
  qanta.guesser.tfidf.TfidfGuesser:
    - enabled: false
      luigi_dependency: qanta.pipeline.guesser.EmptyTask
      random_seed: null
  qanta.guesser.vw.VWGuesser:
    - luigi_dependency: qanta.pipeline.guesser.EmptyTask
      enabled: false

      multiclass_one_against_all: false
      multiclass_online_trees: true
      l2: 0.000001
      l1: 0
      passes: 20
      learning_rate: 0.1
      decay_learning_rate: 0.95
      bits: 29
      ngrams: [1, 2]
      skips: [1]
      random_seed: null
