# partitions: dpart,gpu
# dpart qos: batch=1-00:00:00, deep=12:00:00
# gpu qos: gpu-short=02:00:00
#          gpu-medium=1-00:00:00
#          gpu-long=4-00:00:00
#          gpu-epic=10-00:00:00


default:
  partition: dpart
  qos: batch
  mem_per_cpu: 8g
  max_time: "1-00:00:00"
  gres: null
DanGuesser:
  partition: gpu
  gres: gpu:1
  mem_per_cpu: 16g
  qos: gpu-short
  max_time: "2:00:00"
  cpus_per_task: 4
  mem_per_cpu: 4g
RnnEntityGuesser:
  partition: gpu
  gres: gpu:1
  mem_per_cpu: 16g
  qos: gpu-medium
  max_time: "1-00:00:00"
  cpus_per_task: 4
  mem_per_cpu: 4g
VWGuesser:
  mem_per_cpu: 14g
  cpus_per_task: 1
