# partitions: dpart,gpu
# dpart qos: batch=1-00:00:00, deep=12:00:00
# gpu qos: gpu-short=02:00:00
#          gpu-medium=1-00:00:00
#          gpu-long=4-00:00:00
#          gpu-epic=10-00:00:00


default:
  partition: dpart
  qos: batch
  mem_per_cpu: 4g
  max_time: "1-00:00:00"
  gres: null
  cpus_per_task: 4
  account: c_cluster
DanGuesser:
  partition: gpu
  gres: gpu:1
  qos: gpu-short
  max_time: "2:00:00"
  mem_per_cpu: 4g
RnnGuesser:
  partition: scavenger
  qos: scavenger
  account: scavenger
  gres: gpu:1
  max_time: "1-00:00:00"
  mem_per_cpu: 4g
VWGuesser:
  mem_per_cpu: 14g
  cpus_per_task: 1
ElmoGuesser:
  partition: gpu
  gres: gpu:1
  max_time: "4-00:00:00"
  mem_per_cpu: 4g
  cpus_per_task: 4
  qos: gpu-long
